### ISSUE TITLE
Use of external reverse proxy

### ISSUE THREAD

**Issue by geelenbert** [TechPerplexed/Gooby#121]
Currently my Gooby server is running on a VPS. 

But I want to move it to my home server for various reasons (I got Fiber, HW acc, costs etc..)
The problem is, I already have a reverse proxy running in my home environment. 

What is the easiest way to use an external reverse proxy ?

**Comment by geelenbert** [comment]
Will find another solution, closing issue.

**Comment by geelenbert** [comment]
Is there a simple way to do this?

On my local home I can't have a single dedicated ip to forward to the Gooby vm.

**Comment by geelenbert** [comment]
I would really like some guidance on this one. 

I love how Gooby works. I just need to access the containers directly without the build in reverse proxy. I cant seem to figure out how this should be done.... please help?

**Comment by TechPerplexed** [comment]
I'm sorry @geelenbert  I was hoping someone else would chime in because frankly I have no idea either... I'll leave this open for a while hoping someone knows of a solution :)

**Comment by bdschuster** [comment]
@geelenbert i'm sorry, but what do you mean by you already have an "external reverse proxy"? I'm running a server on my home network for OTA TV purposes, but i'm not quite sure what the problem is  that wouldn't make it work for you? I'm just NATing 8443, 80, and 443 to my internal server and everything is working as it should. You probably don't even need 80 to be forwarded. I do it for other reasons.

**Comment by geelenbert** [comment]
I Hope this picture explains what i want to accomplish:

![image](https://user-images.githubusercontent.com/91923/77058659-0a99f080-69d6-11ea-91fb-98c5d07cf346.png)

If i add an entry in my Nginx reverse proxy that forwards : goobyserver.com to 192.168.1.70, i get errors like "DNS_PROBE_FINISHED_NXDOMAIN" 

Also Gooby's reverse proxy cant get let's encrypt certificates.

What would be the way to go ?

**Comment by TechPerplexed** [comment]
Well, I asked @kelinger, who is the brain behind Gooby. According to him, running Gooby at home should pretty much be the same as running it on a VPS.  If you set it up right, any port that you’re exposing will need to be forwarded from your router (Linksys, D-Link, etc.). 

So, without the torrent part, that “should” just be 80 and 443 (and if all you’re going to do with 80 is tell the browser to use 443, you really just need 443).  Now, if you’re also using BitTorrent, you’re going to need to open that up as well.  All of those ports on your router will be forwarded to the main internal IP of your box running Docker.

More generic answer:  If you go to the /var/local/Gooby/Docker folder and type `docker-compose ps` you’ll get an output somewhat like this:

![docker](https://user-images.githubusercontent.com/15312691/77182230-a9cbf000-6a89-11ea-9452-c77d4f7fc6de.jpg)

Now, the column on the right shows you what ports each Docker is using.  However, anything that doesn’t have 0.0.0.0 means that it is using that port internally (container to container) so it’s only the 0.0.0.0 ones that need to be opened publicly.  So, if I were going to move Gooby to my home, I’d need to point 80, 443, 51413, 51414, 6881, 8000, and 3306 from my router to my box running Docker.  Again, that’s the MAX ports you’d need to open.  I may decide I don’t want my MySQL server open to the public so I wouldn’t open it on the router.

And, to be clear, what I mean by “open” is to use the routers “port mapping” or “port forwarding” feature. You’d also want to make sure your DNS entries (emby.mydomain.com, etc.) all point to the external IP of your home router. 

Does that help you somewhat?

**Comment by geelenbert** [comment]
Well almost...

I think this does show my setup:
![image](https://user-images.githubusercontent.com/91923/77524855-5e01b800-6e88-11ea-9dd0-5f8f4162f8c1.png)

As you can see, i allready have a reverse proxy at home ([jc21/nginx-proxy-manager](https://github.com/jc21/nginx-proxy-manager))

I own 2 domains, domain1 (my personal domain for for example nextcloud home automation and other stuff. One domain (goobyserver.com) is now pointed to a VPS. It realy works smooth! 
But i want to move the Gooby setup to a local VM with HW acceleration. 

**First option:**
So the ideal situation would be, adding a reverse proxy entry to my existing reverse proxy and forward port 80 and 443 to 192.168.1.70:443. But if i do this, i get the error "DNS_PROBE_FINISHED_NXDOMAIN", and i see that the gooby VM did not create the let's encrypt SSL certificates.

**Second option:**
Next option would be to create reverse proxy entries in my existing reverse proxy server:
emby.goobyserver.com -> 192.168.1.70:8096
radarr.goobyserver.com -> 192.168.1.70:7878
sonarr.goobyserver.com -> 192.168.1.70:8989
nzbget.goobyserver.com -> 192.168.1.70:6789

But these apps don't have their ports avaialble to the public at this moment, as should be on the VPS.
![image](https://user-images.githubusercontent.com/91923/77526377-bd60c780-6e8a-11ea-9c68-0c79472b0d5c.png)

I would prefer to have the the first option working, but what should i do ?

**Comment by kelinger** [comment]
Well, you're kind of bypassing a lot of things that Gooby was built for.  Yes, you CAN expose the ports like 8096, 7878, etc. to OUTSIDE the container, and indeed, that's what you're going to need to do.  But, since Gooby already has a reverse proxy, the issue is that your non-Gooby stuff is running essentially on a different network.

Today, only 443 is open which goes to the Gooby reverse proxy and then locally (ie, within Docker's network created for the Gooby stack) to the respective containers.  In either case, the workload is being handled by your own proxy, not the Gooby one, so the mapping of domains, URLs, and any masquerading would/should be handled by that (first option).

For your second option, you'd need to expose the port(s) you want so that they are not going through any kind of second proxy (which is where your issues mostly lie) and thus, the server's non-public IP with the specific ports would respond accordingly.  You may still have to map or address things like Plex's URL within the Plex config (same for Emby).

Ken
