### ISSUE TITLE
Sonarr / Radarr copying completed NZB files & not moving.

### ISSUE THREAD

**Issue by verycoolm8** [TechPerplexed/Gooby#125]
Hello, having a weird issue with Sonarr / Radarr when downloading via nzbget (Also happening with Deluge but I'm assuming it will always copy due to seeding so not as concerned)

When the downloads are finishing they are _copying_ the completed folder from my NZBGet download folder (`/Downloads/nzbget`) to `/Downloads` and causing a much longer delay when trying to add content. I thought it may be an issue with Sonarr / Radarr but they are all configured correctly as far as  I can tell so thought i'd ask here.

If I manually download a file via nzbget into `/Downloads` then move it myself into the `mnt/uploads `folder it moves instantly & appears straight into Plex so it's definitely copying or doing something weird.

Any ideas? ty.

**Comment by TechPerplexed** [comment]
I'm not sure what could be the problem, except somehow your script seems to think that the files have to be moved to another drive... which causes the copy.

I am not familiar with nzbget, but my settings in Deluge are

![Deluge](https://user-images.githubusercontent.com/15312691/79923475-6f3bd700-83ea-11ea-8b40-c1e1dd897cec.jpg)

So it moves from /Downloads/folder1 to /Downloads/folder2 which definitely movies the file, not copies. Do you have a similar setup?

**Comment by verycoolm8** [comment]
Is there anything in Gooby or rclone that could cause Radarr / Sonarr to think those folders are on a different drive?

![image](https://user-images.githubusercontent.com/62038160/79929383-e32cbc80-8488-11ea-937b-565a6b2694c7.png)

If I manually move files between any of those folders it is instantaneous so it seems it's just radarr and sonarr getting confused.

**Comment by verycoolm8** [comment]
https://github.com/Cloudbox/Cloudbox/wiki/Downloading-into-the-unionfs-mount

I found this on the Cloudbox Wiki which explains why Docker thinks it's a different file system and copying but when I try and change my folders to /mnt/uploads/Downloads/nzbget I receive `(/mnt/uploads/Downloads/nzbget): could not create directory /mnt/uploads: Permission denied`

**Comment by verycoolm8** [comment]
Okay so I reinstalled NZBGet and it let me change the downloads folder to /Downloads but Sonarr and Radarr are still copying the completed file. 

![image](https://user-images.githubusercontent.com/62038160/79973794-860e2680-84db-11ea-9f09-f7c54887a380.png)

I'm at a loss.

**Comment by TechPerplexed** [comment]
Hmm, very strange, based on your setup it should definitely move, not copy. Perhaps @bdschuster has some thoughts on how he set his up?

**Comment by verycoolm8** [comment]
From what I can gather it's Sonarr & Radarr causing the copying. When they are doing the renaming they think the Download folder and the upload folder are on two different file systems so they are processing a copy instead of a move. But I don't know how to resolve it!

**Comment by TechPerplexed** [comment]
I honestly don't know either... I don't nzbget personally. I'll leave this question open hoping for someone knowledgeable to chime in!

**Comment by verycoolm8** [comment]
Thanks.  It's not the most urgent thing but it'd be nice to be able to download season packs that didn't take 80gb instead of 40gb because they are copying. I've also noticed that if I queue alot of downloads then I can download quicker than my VPS can copy / extract so it can get backed up very quickly and then cut out because it hits the storage limit.

**Comment by bdschuster** [comment]
So i know what the problem is here. And I have this problem myself, but since i don't download 1000 things at once at all times :-) it isn't always a problem for me. I do come across this downloading an entire season packed into one as you noted above, then i have to fallback to downloading individual episodes. Let me ponder a moment, and see if i can figure out a way you can do this. It is mostly what you said, but is a combination of NZBGet/Dulge/Sab and Radarr/Sonarr that is causing it, not just NZBGet.
I'll explain: NZB/Dulge/Sab all download to /Downloads/completed, totally fine, no issues. Then Sonarr/Radarr picks up that it completed, and attempts to "move" the file to /Media/(your google drive folder), which docker considers a different volume, so it "copies", not moves. 
I'm not sure there is going to be an "easy" way to fix this, as you don't want the "completed" folder inside the google drive folder as it will attempt to copy/move things that download immediately to Google Drive, which you don't want to do, that will cause more issues, and even slower than what it is doing now.
So yeah, let me ponder on this.

**Comment by mr-handerson** [comment]
Any particular reason why you're changing the nzbget paths from default?

![image](https://user-images.githubusercontent.com/54524566/80250793-5ec56f80-8629-11ea-93a1-40aeca3b77a0.png)

Also, if I understand correctly how everything links together, /mnt/* is rclone territory. It is the volume(s) external to the docker container. This is essentially a mapping of your Google drive and you don't want to be dealing with anything /mnt/ directly. 

/mnt/uploads is symlinked so I don't think you can directly interact

/mnt/google should be mounted as /Media with the *arr containers. /Media is not mapped as a volume in NZBGET which is why you get a permission denied error when trying to access, create. /Downloads is mapped to the same location in NZBGET and the *arrs and this is where you should be operating within. 

However due to rclone sync not being instant, I believe there is a 'copy' of sorts within /mnt/ between /mnt/uploads/Downloads and /mnt/google/Downloads while rclone does its thing. I think this is by design though to ensure rsync is only trying to upload completed files.

However, my suggestion would be to start by defaulting the paths and see if that helps.

**Comment by TechPerplexed** [comment]
I don't profess to know as much as @bdschuster on the matter, but that is one reason why we created the constructions of virtually placing the downloads folder within the /mnt/google folder (/mnt/google/Downloads).

When Gooby moves files, physically they move across on the same level from /mnt/Google/Downloads to /mnt/Google/somefolder (thus being a proper "move", not a copy). 

As you guys said, if you move files from /mnt/uploads to /mnt/google, it thinks it is moving from one drive to another and reacts accordingly (copies the file, waits till it's on the other side, then removes the original). 

MergerFS should know the difference so I'm really puzzled why it's behaving this way... it definitely needs some thinking here... especially since it's working just fine on Deluge.

**Comment by bdschuster** [comment]
@TechPerplexed , so within the Docker Container for Sonarr/Radarr, you have 2 mounts:
/Downloads and /Media, remember, docker doesn't care what they are mapped to outside of the container, it just sees them as 2 volumes, which forces the copy (copies the file to /Media, then deletes the one from /Downloads, casing double the space usage until copy is complete), instead of move (directly relocates the file without casing the double storage usage).

Your Deluge thing puzzles me, if you are using Sonarr/Radarr with Deluge, then it will never move, only copy (hard link) because it's a torrent and doesn't want to screw up seeding.

As far as a fix for this, it would be a simple(ish) change, but would require some changes to the Docker YAML for NZBGet, we would need to add  `- ${MEDIA}:/Media`  to NZBGet YAML file, then change the MainDir in NZBGet to `/Media/Downloads` . Since the `/Media` mount already exist in Sonarr/Radarr, no additional configuration would need to be done with them. This would then make the docker container happy because it would simply be moving from /Media/Downloads/completed to their /Media/(YOURCONTENT) and not another "Volume".

And as for @mr-handerson 
![image](https://user-images.githubusercontent.com/38221778/80262762-26875680-8654-11ea-9449-85f3291b6aae.png)

**Comment by bdschuster** [comment]
Just tested my theory and it did work. Adding the media mount to NZBGet and changing the maindir in NZBGet to /Media/Downloads works as expected and is "moving" the files as opposed to "copying". And holy crap, i forgot how much faster Sonarr/Radarr processes files when it doesn't have to copy them! This may be something we will want to change.

**Comment by verycoolm8** [comment]
Sorry for the delay, just realized I didn't reply. Doing what bdschuster did completely fixed the issue. 
Instant Moves after NZB's finish instead of copying, so much quicker! Thanks guys.

**Comment by bdschuster** [comment]
@verycoolm8 I'm so happy this worked for you, since both me and you tested this, I will work with @TechPerplexed to implement this for future updates. 

@TechPerplexed Sorry, i've been incredibly busy lately, I will reach back out soon so we can discuss.

**Comment by TechPerplexed** [comment]
@bdschuster no worries bud :) I guess we're all kinda swamped right now, haha!
