### ISSUE TITLE
Can't stop/restart Plex after some time

### ISSUE THREAD

**Issue by Coxeroni** [TechPerplexed/Gooby#127]
VPS with Ubuntu 18.04
Gooby 2.2.1
Docker version 19.03.8
Command `docker restart plex`
When trying to stop/restart the Plex container after running for some time, I merely get a timeout from docker and the command cannot be executed. Other containers work fine and Plex can also be restarted after a fresh reboot. So something happens "over time".

I don't know what kind of logs would be needed but I am happy to supply them if needed. 

Grateful for any help.

**Comment by TechPerplexed** [comment]
Hi Coxeroni, nice to see you again :)

The good news is: this has been happening since day 1... and we're pretty convinced it has nothing to do with Gooby (it seems to be a docker problem). 

The bad news of course is that since we're pretty convinced that this is a problem within docker itself, we have no solution :( It seems to happen randomly and at random intervals. I had it for months on end, then rebuild the server one day and it never occurred again.

So unfortunately it's not something I/we know a solution to. It's not truly crippling because a reboot sorts it, at least, as you said, for a while. sorry I don't have better news! At least know you're not suffering alone 😄

**Comment by Coxeroni** [comment]
You too, hope you are alright and healthy. 

I see, thanks for letting me know! Well Debian would certainly be an option, but currently I am not in the mood of rebuilding, since I currently use my VPS merely as a backup server and for my friends. I will live with this flaw then, not too dramatic. 

Take care

**Comment by Adoruta** [comment]
I had the same issue using Ubuntu (18 and 20). Jumping over to Debian 10 resolved those issues. I couldn't work out the problem, but Debian appears rock solid.

**Comment by Coxeroni** [comment]
Interesting, but I am not planning on rebuilding my VPS ;)
