### ISSUE TITLE
Installing Portainer

### ISSUE THREAD

**Issue by falcomm6** [TechPerplexed/Gooby#136]
Hi there,

Looks like gooby now allows selection of portainer version. My issue is that there's nothing listed. I havent worked out what to enter. Can you please advise?

![image](https://user-images.githubusercontent.com/67247329/92557203-04167280-f2af-11ea-8bdf-6befea25831f.png)

Thanks
Matt

**Comment by mr-handerson** [comment]
I think this might be because in the install scripts the subheading organizers and portainer both start with 10-
All the other categories don't overlap. @TechPerplexed will need to check and confirm though, and I could also be completely off the mark.

Versions typically prompt for (S)table or (B)eta versions, so you could try selecting S for stable and see if that will get the installation to proceed. Failing that you'll probably have to wait for a fix.

**Comment by TechPerplexed** [comment]
Thanks for the heads-up, @mr-handerson 🙂 Unfortunately I can't check anything right now, because we're having a major power outage (almost 3 days and counting)

Would it be possible for you to manually copy the version across to the /var/local/Gooby/Docker/components folder until I can sort the menu, @falcomm6 ?

**Comment by falcomm6** [comment]
hmm. Something went very wrong. rclean completely botched my system. all mounts deleted, says all my applications are not installed. When I try to reinstall rclone I get permission issues. 

I dont have a backup as I had a big issue with crypt (which I learned my lesson on). Bummer.

**Comment by bdschuster** [comment]
@falcomm6 did you get any errors? Nothing I did should have completely botched everything, I ran rclean several times on 2 different systems and no issues.

**Comment by falcomm6** [comment]
Worked it out. rclone caused some issues - somehow it got muddled up (as it does) then due to the rclean not completing, the apps werent installed.

I deleted all contents of my rclone mount - uninstalled/reinstalled with some weird behavior a few times but _eventually_ got it working.

The only error I got was a lot of mount fails. TBH the only issues I ever have with gooby turns out to be rclone related. I purged 30tb of files as the encryptor just stopped playing ball - even with the correct salt & pepper (had restored multiple times in the past, but after days of reformats I wrote it off). 

Anyway, case closed - will run a backup now. Love your work and thank you.
