### ISSUE TITLE
Emby Image correction.

### ISSUE THREAD

**Issue by shadowsbane0** [TechPerplexed/Gooby#202]
This may be a just me issue but image pull “emby/embyserver” fails on entry error. In all fairness it was doing that to me on Gooby as well. When I changed it to “lscr.io/linuxserver/emby:latest” I was good to go.

**Comment by TechPerplexed** [comment]
Hmmmm weird, that seems to be the official server. I can't say I experienced this issue myself.

If you are referring to OmniStream, you can't just edit containers, but you'll need to copy it to the 800 range to make it a personal one. You couldn't possibly know that because we haven't even written the documentation yet, but just a heads up since you took the dive 😁

You'll find that after `omni refresh` all your changes to existing containers will be reverted.

**Comment by TechPerplexed** [comment]
Closing this since we have a similar discussion going on "the other page" too :)
