### ISSUE TITLE
[question] Deluge permission problems?

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#22]
with the fear of having another non-issue I'm experiencing some issues wit Deluge.

When installed the default download location is /root/Downloads. When adding a torrent Deluge returns an error saying that Deluge does not have permissions to /root/Downloads. 

I tried to change it to /home/plexuser/Downloads and /plexuser/Downloads/ but in both cases the torrent does not download. There is a Down speed, which slowly drops to zero, but nothing under Downloaded in Deluge and when I go the the CLI I see no files created in /home/plexuser/Downloads.

It could indicate that Deluge does not have the right permissions. Or I did something wrong again ;-)

I removed Deluge, ran system cleanup and reinstalled Deluge. No luck :-(

P.S.
Before Gooby I installed all the apps myself and did not have such problems. I mean, the server/ext. IP is tried and tested :-)

**Comment by TechPerplexed** [comment]
Ack! You might be right there... let me check on that. Once again thank you for your thorough testing - and pleasant attitude about it all :)

**Comment by TechPerplexed** [comment]
Definitely an issue... I just hadn't noticed it yet. On it now!

**Comment by TechPerplexed** [comment]
It should work now. Please uninstall Deluge (no need to remove user files) and reinstall... that should do it.

Just as a heads up (and definitely one to add to the upcoming wiki):

Make sure you point Download to to /Downloads (not your home folder)

![screenshot 2018-10-27 15 34 45](https://user-images.githubusercontent.com/15312691/47609950-4493dc80-da06-11e8-98a3-a3b71f9a2d13.png)

Thanks again for finding this bug :)

**Comment by deedeefink** [comment]
It works. Thanks

**Comment by deedeefink** [comment]
I might have been a bit too fast there.
Deluge can now download files to /Downloads, but it seems that Radarr/Sonarr and I would assume NZBGet, might not have the permission to move the file into place after download completed?

When the torrent finished Radarr marked it as import fail "No files found are eligible for import in /Downloads". Same result if I try to import the file manually via Radarr.

**Comment by TechPerplexed** [comment]
Thanks once again, it's sorted now. You will need to update Gooby, and then uninstall (without deleting user settings!) and reinstall both Radarr and Sonarr.

I did however find an inconsistency so far, where Plex points to /Media as its media folder, Emby to /Media/Google and Sonarr/Radarr to just plain /Google.

They have all been changed to point to /Media now (which I believe is is the most logical name). Please change your root folder in both Sonarr and Radarr to point to /Media/ folder and then your movie/TV folder respectively - this should be a one time update. 

So, in Radarr, click Movie editor
Select all movies
Change the root folder to /Media/Movies
Then click "Organize"

Please check your Emby installation if it points to just /Media (instead of /Media/Google) If ever you uninstall Emby and reinstall it you may encounter the same missing root folder otherwise...

My apologies for inconvenience!

Oh one last thought: make sure you pick /Media (capital M) and not /media - this is another inconsistency I plan to work on, but that is for a future date and should go largely unnoticed, hopefully :)

**Comment by TechPerplexed** [comment]
Thanks once again, it's sorted now. You will need to update Gooby, and then uninstall (without deleting user settings!) and reinstall both Radarr and Sonarr.

I did however find an inconsistency so far, where Plex points to /Media as its media folder, Emby to /Media/Google and Sonarr/Radarr to just plain /Google.

They have all been changed to point to /Media now (which I believe is is the most logical name). Please change your root folder in both Sonarr and Radarr to point to /Media/ folder and then your movie/TV folder respectively - this should be a one time update.

So, in Radarr, click Movie editor
Select all movies
Change the root folder to /Media/Movies
Then click "Organize" and "Save" (this could take a while, it's what threw me at first)

Sonarr is pretty similar, if you're using their excellent new version just go to series - mass editor, done.

Please check your Emby installation if it points to just /Media (instead of /Media/Google) If ever you uninstall Emby and reinstall it you may encounter the same missing root folder otherwise...

My apologies for inconvenience!

Oh one last thought: make sure you pick /Media (capital M) and not /media - this is another inconsistency I plan to work on, but that is for a future date and should go largely unnoticed what that takes place, hopefully :)

**Comment by deedeefink** [comment]
Now it works. Thank you kind Sir
