### ISSUE TITLE
OMBI Issue

### ISSUE THREAD

**Issue by bdschuster** [TechPerplexed/Gooby#33]
Do you hate me yet? 🤣 
1st: the ombi image needs netstat (net-tools) installed on it for the health monitor to work, otherwise it shows unhealthy. I already installed it on mine, just an FYI.

2nd: I'm having issues with Orginizr talking back to OMBI. Never had this issue before, i thought i would run it by you. I have Organizr talking to Sonarr/Radarr/Plex/NZBGet with no issues, but OMBI, i get this in the logs of Organizr: OMBI Connect Function - Error: cURL error 35: error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

Any ideas?

**Comment by TechPerplexed** [comment]
Haha neverrr!

1st - more information please, what did you do to install netstat to benefit all Ombi users? 😸 

2nd - ok wait what language did you just speak? 😆 Seriously though, no idea... honestly... that could just be anything at all!

**Comment by bdschuster** [comment]
1. Actualy you don't need to install it, i'm special...i forgot you just make a mount to it from outside the container. Super easy, edit your Gooby/scripts/components/60-ombi.yaml file to include the bold line:
` volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/Ombi:/config
      - ${GOOGLE}:/Media
      **- /bin/netstat:/bin/netstat**`
Now OMBI is healthy. 😺 

2. I think it may be something to do with the SSL version...I'm not sure how to fix that 😢 

I have a suggestion for another edit on your sync script. Want another issue? or talk about it here?

**Comment by TechPerplexed** [comment]
Thanks for the file! I have merged the pull request.

What other edit would you like to suggest? You can shoot here :)

**Comment by bdschuster** [comment]
the 2 minute min file age in your sync script that runs every 15mins, I see some issues with it already with tonights downloads. 1. If you have Sonarr set to change the file time to the air date/time (advanced settings in media management), and it downloads early (Select shows have been available on-demand at midnight before air date), the file date/time gets changed to a future time, potentially up to 10-11 hours. so when the script runs, it doesn't upload it till after whenver the air date/time is. Now, I can turn that option off, but 2. Sometimes the uploader does the same thing after processing, or his time is just wrong, and it's also in the future, holding the upload.

Now you could edit the script and add something like:
`find ${UPLOADS}/ ! -path "*Downloads*" -type f -exec touch {} +`
at the end of the file, but that could potentially be, at the most, a 30min delay for the upload.

You could also update your delay to use "amin" instead of "mmin", as that seems to be acurate to when it was created, but i don't know how you could update the rclone move command to use acess time instead of modify time.

What was the reason for the 2min delay?

What do you think?

**Comment by TechPerplexed** [comment]
First, thanks for all your suggestions and reports - they are helpful in creating the ultimate stable system :)

To answer you first question: the 2 minute delay is just to make 100% sure the file isn’t still being written to.  Yes, it is likely overkill.  At the same time, the date isn’t set until the file write is completed (in instances where the date is changed).  So, assuming a file finishes writing at 1:59:59.999999 and the process kicks off, it will show that the file is 1m old.  In reality, it is a few milliseconds old and there is the [albeit, remote] chance that the next bit is in a buffer and hasn’t been dumped to the disk yet.  Making it 2 minutes ensures that this special case won’t occur.  Odds of it occurring:  remote.  Odds of it occurring to someone at some point:  likely 😆 

As for the “future” times, my friend and co-creator of Gooby (heck, who am I kidding, he's the real brain behind all this) reported he has had this happen to him as well.  A file date/time may be in the future if an episode is downloaded early or if a date is set but not a time.  However, these aren’t overly frequent enough to be worried about lost data.  Agreed that touching the file will set the current date/time but he prefers to let *arr set those since he'd prefer to have them match the originals. And he's the bossman haha!

That said if this proves to be really troublesome to you please report back and we'll reconsider... and of course you are more than welcome to copy a modified cron script to your home directory and have the crontab use that instead :)

**Comment by bdschuster** [comment]
Thanks! Will do, glad i'm not the only one who has the issue. This is what I added to end of your script:
`# Correct future file times to pick up next sync`

`echo Correcting future file date/times.. | tee -a ${LOG}`
`find ${UPLOADS}/ ! -path "*Downloads*" -type f -exec touch {} + | sed 's|'${UPLOADS}'||' | sort > /tmp/futurefiles`

`if [[ -s /tmp/futurefiles ]]`
`then`
`        cat /tmp/futurefiles | tee -a ${LOG}`
`        echo Files to copy next sync: $(cat /tmp/futurefiles |wc -l) | tee -a ${LOG}`
`else`
`        echo No future files to correct | tee -a ${LOG}`
`fi`
``
`# Cleanup letovers`
``
`rm /tmp/filesmissing`
`rm /tmp/futurefiles`
`cd ${UPLOADS}`
`find . -type d -empty -delete`
`mkdir -p ${UPLOADS} ${UPLOADS}/Downloads`
`echo Finished at $(date) | tee -a ${LOG}`
`echo --------------------------------------------------- | tee -a ${LOG}`


Now just an FYI, if you still want want *arr to change the file times, you can, when it does it's 12 hour scheduled scan, it will correct those file times if they are not correct.

Since i have it logging, I will keep an eye and see if I am getting a lot.

**Comment by TechPerplexed** [comment]
Let me know! If it turns out to be working much better all around, then naturally it would make sense to implement it for all :)

I'll close this in the meantime... Since it really started out with Ombi haha.
